- name: Common Configuration for All Machines
  hosts: all, localhost
  become: yes
  tasks:
    - name: Install EPEL repository on RedHat-based systems
      yum:
        name: epel-release
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install essential packages on RedHat-based systems (excluding virtualenv)
      yum:
        name:
          - glibc-langpack-en
          - vim
          - emacs
          - nano
          - screen
          - tmux
          - net-tools
          - bind-utils
          - htop
          - git
          - curl
          - wget
          - python3
          - python3-pip
          - python3-devel
          - pigz
          - firewalld
          - python3-firewall
          - patch
          - bzip2
          - make
          - nfs-utils
          - links
          - unzip
          - ufw
          - java-11-openjdk
          - java-11-openjdk-devel
        state: present
      when: ansible_os_family == "RedHat"
      register: install_redhat
      # Retry up to 3 times, waiting 5 seconds between tries, until the task succeeds.
      retries: 3
      delay: 5
      until: install_redhat is succeeded


    - name: Upgrade pip to the latest version on all machines
      pip:
        name: pip
        executable: pip3
        state: latest

    - name: Install virtualenv using pip
      pip:
        name: virtualenv
        executable: pip3
        state: latest

    - name: Ensure firewalld is installed on RedHat-based systems
      package:
        name: firewalld
        state: present
      when: ansible_os_family == "RedHat"

    - name: Ensure firewalld is running and enabled on RedHat-based systems
      systemd:
        name: firewalld
        state: started
        enabled: yes
      when: ansible_os_family == "RedHat"

    - name: Allow HTTP and HTTPS in firewall
      firewalld:
        service: "{{ item }}"
        state: enabled
        permanent: yes
      loop:
        - http
        - https
      notify: reload firewalld

    - name: Ensure Nginx is installed on all machines
      package:
        name: nginx
        state: present

    - name: Install Certbot on RedHat-based systems
      yum:
        name:
          - certbot
          - python3-certbot-nginx
        state: present
      when: ansible_os_family == "RedHat"

    - name: Install Apache httpd
      yum:
        name: httpd
        state: present

    - name: Start and enable Apache httpd
      systemd:
        name: httpd
        state: started
        enabled: yes

    - name: Set en-GB localization
      shell: "localectl set-locale en_GB.UTF-8"

    - name: Create /etc/hosts from template
      ansible.builtin.template:
        src: "../templates/hostfile.j2"
        dest: "/etc/hosts"
        owner: "root"
        group: "root"
        mode: "0644"

    - name: Add hadoop temporary directory
      ansible.builtin.file:
        path: /opt/hadoop_tmp
        owner: almalinux
        group: almalinux
        state: directory

    - name: Add HDFS directory
      ansible.builtin.file:
        path: /opt/hadoop_tmp/hdfs
        owner: almalinux
        group: almalinux
        state: directory

  handlers:
    - name: reload firewalld
      systemd:
        name: firewalld
        state: reloaded
