- name: Update mgmt node inventory
  hosts: mgmtnode
  gather_facts: false
  become: yes
  become_method: sudo
  vars:
    ansible_ssh_common_args: >-
      -o StrictHostKeyChecking=no
      -o UserKnownHostsFile=/dev/null
      -o GlobalKnownHostsFile=/dev/null
      -o ProxyJump=condenser-proxy
      -o BatchMode=yes
      -o IdentityFile=~/.ssh/ansible_ed25519
  tasks:
    - name: Wipe known_hosts entirely on local
      delegate_to: localhost
      run_once: true
      shell: "truncate -s 0 ~/.ssh/known_hosts"
      become: false

    - name: Copy private key from LOCAL to mgmt node
      ansible.builtin.copy:
        src: "{{ lookup('env','HOME') }}/.ssh/ansible_ed25519"
        dest: /home/almalinux/.ssh/ansible_ed25519
        owner: almalinux
        group: almalinux
        mode: '0600'

    - name: Wait until the inventories directory is present
      become_user: almalinux
      wait_for:
        path: /home/almalinux/data-pipeline/ansible/inventories
        state: present
        delay: 5
        timeout: 120
        msg: "data-pipeline/ansible/inventories folder never appeared on the mgmt node."

    - name: Copy updated inventory.json to mgmt node
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/../../ansible/inventories/inventory.json"
        dest: /home/almalinux/data-pipeline/ansible/inventories/inventory.json
        owner: almalinux
        group: almalinux
        mode: '0644'
