- name: Install and Configure Distributed MinIO on Workers
  hosts: worker_inventory
  become: true
  vars:
    minio_root_user: "admin"
    minio_root_password: "Min10S3P@ss"  # Replace with a secure password
    # Use the extra disk mounted at /mnt/data
    minio_server_datadirs:
      - "/mnt/data"
    minio_install_server: true
    minio_install_client: true
    # Explicitly set the server port and URL for the alias command
    minio_server_port: 9090
    minio_unsecure_url: "http://127.0.0.1:9090"
  pre_tasks:
    - name: Build MinIO cluster endpoints from inventory
      set_fact:
        minio_server_cluster_nodes: "{{ groups['worker_inventory'] 
          | map('extract', hostvars, 'ansible_host') 
          | map('regex_replace', '^(.*)$', 'http://\\1:9090/mnt/data') 
          | list }}"
  tasks:
    - name: Dynamically include the ricsanfre.minio role
      include_role:
        name: ricsanfre.minio
