- name: Ensure Ansible Galaxy Dependencies and Essential Packages on Control Node
  hosts: localhost
  gather_facts: yes
  become: yes

  tasks:
    - name: Check if community.general collection is installed
      stat:
        path: "{{ lookup('env','HOME') }}/.ansible/collections/ansible_collections/community/general"
      register: community_collection

    - name: Install community.general collection if not present
      command: ansible-galaxy collection install community.general
      when: not community_collection.stat.exists
      register: collection_install

    - name: Install and Configure Alertmanager on Host
      import_role:
        name: alert_manager

    - name: Install essential system packages for ESM on Host (AlmaLinux)
      dnf:
        name:
          - git
          - python3
          - python3-pip
          - pigz
        state: present
        update_cache: yes

    - name: Install httpd
      yum:
        name: httpd
        state: present

    - name: Ensure httpd service is started and enabled
      systemd:
        name: httpd
        state: started
        enabled: yes

    - name: Install pip if not already installed
      package:
        name: python3-pip
        state: present

    - name: Install Flower (Celery monitoring UI)
      pip:
        name: flower
        virtualenv: "{{ venv_path }}"
        state: latest



