- name: Mount NFS shares on all clients (host and other workers)
  hosts: all, localhost
  become: yes
  gather_facts: yes
  vars:
    nfs_server_ip: "{{ hostvars['worker1'].ansible_default_ipv4.address }}"
    mount_datasets: "/mnt/datasets"
    mount_results: "/mnt/results"

  tasks:
    - name: Install NFS utilities
      yum:
        name: nfs-utils
        state: present

    - name: Create mount points
      file:
        path: "{{ item }}"
        state: directory
        mode: '0755'
      loop:
        - "{{ mount_datasets }}"
        - "{{ mount_results }}"

    - name: Mount NFS datasets
      mount:
        src: "{{ nfs_server_ip }}:/mnt/datasets"
        path: "{{ mount_datasets }}"
        fstype: nfs
        opts: defaults
        state: mounted

    - name: Mount NFS results
      mount:
        src: "{{ nfs_server_ip }}:/mnt/results"
        path: "{{ mount_results }}"
        fstype: nfs
        opts: defaults
        state: mounted
