---
- name: Provision Worker VMs using Terraform
  hosts: localhost
  become: yes
  gather_facts: no

  tasks:
    - name: Ensure DataPipeline directory is owned by almalinux
      file:
        path: /home/almalinux/DataPipeline
        recurse: yes
        owner: almalinux
        group: almalinux

    - name: Ensure python3-pip is installed
      yum:
        name: python3-pip
        state: present

    - name: Remove any existing terraform-inventory file at /usr/local/bin/terraform-inventory
      file:
        path: /usr/local/bin/terraform-inventory
        state: absent

    - name: Download terraform-inventory prebuilt binary for Linux (amd64)
      get_url:
        url: "https://github.com/adammck/terraform-inventory/releases/download/v0.10/terraform-inventory_v0.10_linux_amd64.zip"
        dest: "/tmp/terraform-inventory.zip"
        mode: '0644'
        force: yes

    - name: Unarchive terraform-inventory binary
      unarchive:
        src: "/tmp/terraform-inventory.zip"
        dest: "/tmp/"
        remote_src: yes

    - name: Copy terraform-inventory binary to /usr/local/bin/terraform-inventory
      copy:
        src: "/tmp/terraform-inventory_v0.10_linux_amd64"
        dest: "/usr/local/bin/terraform-inventory"
        mode: '0755'

    - name: Check if Terraform is installed at /usr/local/bin/terraform
      command: /usr/local/bin/terraform version
      register: terraform_installed
      ignore_errors: yes

    - name: Install Terraform if not installed
      shell: |
        echo "Terraform not found. Installing Terraform..."
        yum install -y wget unzip
        TERRAFORM_VERSION="1.5.0"
        wget -O /tmp/terraform.zip "https://releases.hashicorp.com/terraform/${TERRAFORM_VERSION}/terraform_${TERRAFORM_VERSION}_linux_amd64.zip"
        unzip /tmp/terraform.zip -d /usr/local/bin
        rm /tmp/terraform.zip
        echo "Terraform installed."
      when: terraform_installed.rc != 0

    - name: Initialize Terraform in workers directory
      shell: /usr/local/bin/terraform init
      args:
        chdir: /home/almalinux/DataPipeline/terraform/workers

    - name: Apply Terraform configuration for workers
      shell: /usr/local/bin/terraform apply -auto-approve
      args:
        chdir: /home/almalinux/DataPipeline/terraform/workers
