- name: Set Management Node Hostname (mgmtnode)
  hosts: localhost
  become: true
  become_user: root
  tasks:
    - name: Set hostname for management node to "mgmtnode"
      ansible.builtin.hostname:
        name: mgmtnode
        use: systemd

- name: Set Worker Node Hostnames
  hosts: worker_inventory
  become: true
  become_user: root
  tasks:
    - name: Set hostname for worker nodes
      ansible.builtin.hostname:
        name: "workernode{{ groups['worker_inventory'].index(inventory_hostname) + 1 }}"
        use: systemd


