- name: Finalise Hadoop Setup on Management Node
  hosts: localhost
  become: true
  become_user: root
  vars:
    hadoop_home: "/home/almalinux/hadoop-3.4.0"
  tasks:
    - name: Format Hadoop cluster (namenode)
      ansible.builtin.shell: "{{ hadoop_home }}/bin/hdfs namenode -format -force"
      args:
        chdir: "{{ hadoop_home }}"
      environment:
        HADOOP_HOME: "{{ hadoop_home }}"
        PATH: "{{ hadoop_home }}/bin:{{ ansible_env.PATH }}"

    - name: Start HDFS (Distributed File System)
      ansible.builtin.shell: "nohup ./sbin/start-dfs.sh &"
      args:
        chdir: "{{ hadoop_home }}"
      environment:
        HADOOP_HOME: "{{ hadoop_home }}"
        PATH: "{{ hadoop_home }}/bin:{{ ansible_env.PATH }}"

    - name: Start YARN (Resource Manager)
      ansible.builtin.shell: "nohup ./sbin/start-yarn.sh &"
      args:
        chdir: "{{ hadoop_home }}"
      environment:
        HADOOP_HOME: "{{ hadoop_home }}"
        PATH: "{{ hadoop_home }}/bin:{{ ansible_env.PATH }}"
