---
- name: Setup Symbolic Links for Application Data
  hosts: host
  become: yes
  tasks:
    - name: Link datasets directory
      file:
        src: /mnt/datasets
        dest: /var/www/html/datasets
        state: link

    - name: Link results directory
      file:
        src: /mnt/results
        dest: /var/www/html/results
        state: link
